name: Release
on:
  push:
    branches: 
      - master 
      - main

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:

  build:
    name: Build 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - run: mkdir output && mv lib/build/libs/*.jar output/ && ls output

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: algs4.jar
        path: output

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          output/*.jar